name: Choco PowerBI

on: [workflow_dispatch]

jobs:
  choco-powerbi-script:

    runs-on: windows-latest

    steps:
      - run: Install-Package Microsoft.AnalysisServices.NetCore.retail.amd64 -Source 'https://www.nuget.org/api/v2' -scope CurrentUser -Force -SkipDependencies
      - run: Install-Package Microsoft.AnalysisServices.AdomdClient.NetCore.retail.amd64 -Source 'https://www.nuget.org/api/v2' -scope CurrentUser -Force -SkipDependencies
      - run: Install-Package Dax.Vpax.NetCore -Source 'https://www.nuget.org/api/v2' -scope CurrentUser -Force -SkipDependencies
      - run: Install-Package Dax.Model.Extractor.NetCore -Source 'https://www.nuget.org/api/v2' -scope CurrentUser -Force -SkipDependencies
      - run: Install-Package Dax.Metadata -Source 'https://www.nuget.org/api/v2' -scope CurrentUser -Force -SkipDependencies
      - run: Install-Package Dax.ViewVpaExport -Source 'https://www.nuget.org/api/v2' -scope CurrentUser -Force -SkipDependencies
      - run: (Get-Package Dax.ViewVpaExport).Source
      - run: ls 'C:\'
