name: Choco PowerBI

on: [workflow_dispatch]

jobs:
  choco-powerbi-script:

    runs-on: windows-latest

    steps:
      - run: Install-Package Microsoft.AnalysisServices.NetCore.retail.amd64 -scope CurrentUser -Force -SkipDependencies
      - run: Install-Package Microsoft.AnalysisServices.AdomdClient.NetCore.retail.amd64 -scope CurrentUser -Force -SkipDependencies
      - run: Install-Package Dax.Vpax.NetCore -scope CurrentUser -Force -SkipDependencies
      - run: Install-Package Dax.Model.Extractor.NetCore -scope CurrentUser -Force -SkipDependencies
      - run: Install-Package Dax.Metadata -scope CurrentUser -Force -SkipDependencies
      - run: Install-Package Dax.ViewVpaExport -scope CurrentUser -Force -SkipDependencies
      - run: (Get-Package Dax.ViewVpaExport).Source
      - run: ls 'C:\'
