name: Choco PowerBI

on: [workflow_dispatch]

jobs:
  choco-powerbi-script:

    runs-on: windows-latest

    steps:
      - run: Install-Package Microsoft.AnalysisServices.NetCore.retail.amd64 Microsoft.AnalysisServices.AdomdClient.NetCore.retail.amd64 -Source 'https://www.nuget.org/api/v2' -SkipDependencies
      - run: ls 'C:\Program Files\PackageManagement\NuGet\Packages'
