name: Choco PowerBI

on: [workflow_dispatch]

jobs:
  choco-powerbi-script:

    runs-on: windows-latest

    steps:
      - run: choco install powerbi --ignore-checksums
      - run: ls 'C:\Program Files\'
