  
name: Testing random commands

on: [workflow_dispatch]

jobs:
  random-script:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - run: choco install powerbi --ignore-checksums
      - run: pwsh -command "$env:GITHUB_WORKSPACE\process-run.ps1"
