  
name: Testing random commands

on: [workflow_dispatch]

jobs:
  random-script:

    runs-on: windows-latest

    steps:
      - run: choco install powerbi --ignore-checksums
      - run: .\$env:GITHUB_WORKSPACE\process-run.ps1
      - run: Get-Process
