  
name: Testing random commands

on: [workflow_dispatch]

jobs:
  random-script:

    runs-on: windows-latest

    steps:
      - run: pwd
      - run: $env:GITHUB_WORKSPACE
      - run: $GITHUB_WORKSPACE
